[package]
edition = "2018"
name = "ping"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "ping"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}

hdk = "0.0.120"
holo_hash = { version = "0.0.17", features = ["encoding"] }
